# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60eb1dca12d77f6163e8a42ade6ef4ec8cd6d112e4e21e249f2d238670df9dd92a5fdc7cc0e7b733318a8b26a0afff76e81937907a59a334a65c6185708f4ec3

test:
  secret_key_base: c2272a513549c7d129bd76cd90277151e096e18478a8610a93a90e17ad01917357307a48b0dd56fd8044b2cdbcf4c065e6dc85577d2d2a11fc0b3a46dc6cae2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
